CREATE TABLE [dbo].[Cell]
(
	[GRID_ID] INT,
	[ROW_INDEX] INT,
    [COLUMN_INDEX] INT,
    [OBJECT] NVARCHAR(3)
    PRIMARY KEY (GRID_ID, ROW_INDEX, COLUMN_INDEX)
    CONSTRAINT FK_Cell_Grid
        FOREIGN KEY ([GRID_ID])
        REFERENCES Grid([Grid_ID])
        ON DELETE CASCADE
)
