CREATE TABLE [dbo].[Favorite]
(
    [USER_ID] INT,
    [RESTAURANT_ID] INT
    PRIMARY KEY (USER_ID, RESTAURANT_ID)
    CONSTRAINT FK_FAVORITE_USER
        FOREIGN KEY ([USER_ID])
        REFERENCES [User]([USER_ID])
        ON DELETE CASCADE
    CONSTRAINT FK_FAVORITE_RESTAURANT
        FOREIGN KEY (RESTAURANT_ID)
        REFERENCES Restaurant([RESTAURANT_ID])
        ON DELETE CASCADE
)
