CREATE TABLE [dbo].[Reservation]
(
	[RESERVATION_ID] INT PRIMARY KEY IDENTITY,
	[RESTAURANT_ID] INT,
	[USER_ID] INT,
	[RESERVATION_TIME_START] DATETIME,
	[RESERVATION_TIME_END] DATETIME
	CONSTRAINT FK_RESERVATION_RESTAURANT
		FOREIGN KEY ([RESTAURANT_ID])
		REFERENCES Restaurant([RESTAURANT_ID])
		ON DELETE CASCADE
	CONSTRAINT FK_RESERVATION_USER
		FOREIGN KEY ([USER_ID])
		REFERENCES [User]([USER_ID])
		ON DELETE CASCADE
)
