CREATE TABLE [dbo].[Restaurant]
(
	[RESTAURANT_ID] INT PRIMARY KEY IDENTITY,
	[RESTAURANT_NAME] NVARCHAR(30) NOT NULL,
	[RESTAURANT_STREET] NVARCHAR(100) NOT NULL,
	[RESTAURANT_CITY] NVARCHAR(30) NOT NULL,
	[RESTAURANT_POSTCODE] VARCHAR(20) NOT NULL,
	[OWNER_ID] INT,
	CONSTRAINT FK_RESTAURANT_OWNER
		FOREIGN KEY ([OWNER_ID])
		REFERENCES Owner([OWNER_ID])
		ON DELETE CASCADE
)
