CREATE TABLE [dbo].[User]
(
	[USER_ID] INT PRIMARY KEY IDENTITY,
	[USER_LASTNAME] NVARCHAR(50) NOT NULL,
	[USER_FIRSTNAME] NVARCHAR(50) NOT NULL,
	[USER_MAIL] NVARCHAR(50) NOT NULL,
	[USER_PASSWORD] NVARCHAR(50) NOT NULL,
	[USER_PHONE_NUMBER] NVARCHAR(20),
	[USER_DATE_INSCRIPTION] DATETIME DEFAULT GETDATE(),
	[USER_TYPE] NVARCHAR(20) CHECK (USER_TYPE IN ('Owner', 'Customer')),
)
