CREATE TABLE [dbo].[Favorite]
(
    [HUMAN_ID] INT,
    [RESTAURANT_ID] INT
    PRIMARY KEY (HUMAN_ID, RESTAURANT_ID)
    CONSTRAINT FK_FAVORITE_USER
        FOREIGN KEY ([HUMAN_ID])
        REFERENCES Human([HUMAN_ID])
        ON DELETE CASCADE
    CONSTRAINT FK_FAVORITE_RESTAURANT
        FOREIGN KEY (RESTAURANT_ID)
        REFERENCES Restaurant([RESTAURANT_ID])
        ON DELETE CASCADE
)
