CREATE TABLE [dbo].[Grid]
(
	[GRID_ID] INT PRIMARY KEY IDENTITY,
	[GRID_NAME] NVARCHAR(50) NOT NULL,
	[RESTAURANT_ID] INT,
	[GRID_ROWS] INT,
	[GRID_COLUMNS] INT
	CONSTRAINT FK_GRID_RESTAURANT 
		FOREIGN KEY ([RESTAURANT_ID])
		REFERENCES Restaurant([RESTAURANT_ID])
		ON DELETE CASCADE
)
