CREATE TABLE [dbo].[ImageRestaurant]
(
	[IMAGE_ID] INT PRIMARY KEY IDENTITY,
	[RESTAURANT_ID] INT NOT NULL,
	[IMAGE_BLOB] VARBINARY(MAX) NOT NULL,
	[IS_FRONT] BIT
	CONSTRAINT ENSURE_BIT CHECK ([IS_FRONT] IN (0, 1)),
	CONSTRAINT ONLY_ONE_FRONT UNIQUE ([RESTAURANT_ID], [IS_FRONT])
)
