CREATE TABLE [dbo].[ImageRestaurant]
(
	[IMAGE_ID] INT PRIMARY KEY IDENTITY,
	[RESTAURANT_ID] INT NOT NULL,
	[IMAGE_DATA] VARBINARY(MAX) NOT NULL,
	[IS_FRONT] BIT,
	[IS_MENU] BIT
	CONSTRAINT ENSURE_BIT CHECK ([IS_FRONT] IN (0, 1)),
	CONSTRAINT ONLY_ONE_FRONT UNIQUE ([RESTAURANT_ID], [IS_FRONT]),
	CONSTRAINT FK_IMAGE_RESTAURANT
		FOREIGN KEY (RESTAURANT_ID)
		REFERENCES Restaurant(RESTAURANT_ID)
)
