CREATE TABLE [dbo].[ImageRestaurant]
(
	[IMAGE_ID] INT PRIMARY KEY IDENTITY,
	[RESTAURANT_ID] INT NOT NULL,
	[IMAGE_DATA] VARBINARY(MAX) NOT NULL,
	[IS_FRONT] BIT,
	[IS_MENU] BIT
	CONSTRAINT FK_IMAGE_RESTAURANT
		FOREIGN KEY (RESTAURANT_ID)
		REFERENCES Restaurant(RESTAURANT_ID)
)
