CREATE TABLE [dbo].[Rating]
(
	[HUMAN_ID] INT,
	[RESTAURANT_ID] INT,
	[SCORE] TINYINT,
	[COMMENT] NVARCHAR(100)
	CONSTRAINT PK_HUMAN_RESTAURANT
		PRIMARY KEY ([HUMAN_ID], [RESTAURANT_ID])
	CONSTRAINT RATING_HUMAN
		FOREIGN KEY ([HUMAN_ID])
		REFERENCES Human([HUMAN_ID])
		ON DELETE CASCADE
	CONSTRAINT RATING_RESTAURANT
		FOREIGN KEY ([RESTAURANT_ID])
		REFERENCES Restaurant([RESTAURANT_ID])
		ON DELETE CASCADE
	
)
