CREATE TABLE [dbo].[ReservedCell]
(
	[RESERVATION_ID] INT,
	[GRID_ID] INT,
	[ROW_INDEX] INT,
	[COLUMN_INDEX] INT
	PRIMARY KEY (RESERVATION_ID, GRID_ID, ROW_INDEX, COLUMN_INDEX)
	CONSTRAINT FK_RESERVED_CELL_RESERVATION
		FOREIGN KEY ([RESERVATION_ID])
		REFERENCES Reservation([RESERVATION_ID])
		ON DELETE CASCADE
	CONSTRAINT FK_RESERVEDCELL_CELL
		FOREIGN KEY (GRID_ID, ROW_INDEX, COLUMN_INDEX)
		REFERENCES Cell(GRID_ID, ROW_INDEX, COLUMN_INDEX)
)
