CREATE TABLE [dbo].[Reservation]
(
	[RESERVATION_ID] INT PRIMARY KEY IDENTITY,
	[RESTAURANT_ID] INT,
	[HUMAN_ID] INT,
	[RESERVATION_TIME_START] DATETIME NOT NULL,
	[RESERVATION_TIME_END] DATETIME NOT NULL,
	[RESERVATION_STATUS] TINYINT DEFAULT 0
	CONSTRAINT FK_RESERVATION_RESTAURANT
		FOREIGN KEY ([RESTAURANT_ID])
		REFERENCES Restaurant([RESTAURANT_ID])
		ON DELETE CASCADE
	CONSTRAINT FK_RESERVATION_USER
		FOREIGN KEY ([HUMAN_ID])
		REFERENCES Human([HUMAN_ID])
		ON DELETE CASCADE
)
