CREATE TABLE [dbo].[Restaurant]
(
	[RESTAURANT_ID] INT PRIMARY KEY IDENTITY,
	[HUMAN_ID] INT,
	[RESTAURANT_NAME] NVARCHAR(30) NOT NULL,
	[RESTAURANT_STREET] NVARCHAR(100) NOT NULL,
	[RESTAURANT_CITY] NVARCHAR(30) NOT NULL,
	[RESTAURANT_POSTCODE] VARCHAR(20) NOT NULL,
	[RESTAURANT_DESCRIPTION] NVARCHAR(1000),
	[RESTAURANT_RATING] DECIMAL(5, 2) DEFAULT 0
	CONSTRAINT FK_RESTAURANT_OWNER
		FOREIGN KEY ([HUMAN_ID])
		REFERENCES Human([HUMAN_ID])
)
