CREATE TABLE [dbo].[StructuralElement]
(
	[ELEMENT_ID] INT PRIMARY KEY IDENTITY,
	[GRID_ID] INT,
	[ROW_INDEX] INT,
	[COLUMN_INDEX] INT,
	[ELEMENT_TYPE] TINYINT
	CONSTRAINT FK_ELEMENT_GRID
		FOREIGN KEY (GRID_ID)
		REFERENCES Grid(GRID_ID)
		ON DELETE CASCADE
)
